django-bookstore/db-project/bookstore/urls.py
from django.urls import re_path

from . import views

app_name = 'bookstore'
urlpatterns = [
    re_path(r'^$', views.home, name='home'),
    re_path(r'^account$', views.AccountView.as_view(), name='account'),
    re_path(r'^admin$', views.BookstoreAdminView.as_view(), name='admin'),
    re_path(r'^stats$', views.StatisticsView.as_view(), name='stats'),
    re_path(r'^cart$', views.CartView.as_view(), name='cart'),
    re_path(r'^cart/order', views.OrderView.as_view(), name='order'),
    re_path(r'^home$', views.home, name='home'),
    re_path(r'^login$', views.LoginFormView.as_view(), name='login'),
    re_path(r'^logout$', views.LogoutView.as_view(), name='logout'),
    re_path(r'^register$', views.RegistrationFormView.as_view(), name='register'),
    re_path(r'^book/(?P<bid>[a-zA-Z0-9]+)/review-filter-newest/(?P<rnum>[0-9]+)', views.review_filter_newest, name = 'review_filter_newest'),
    re_path(r'^book/(?P<bid>[a-zA-Z0-9]+)/review-filter-best/(?P<rnum>[0-9]+)', views.review_filter_best, name = 'review_filter_best'),
 	re_path(r'^book/(?P<bid>[a-zA-Z0-9]+)/add-to-cart$', views.add_to_cart, name = 'add_to_cart'),
 	re_path(r'^book/(?P<bid>[a-zA-Z0-9]+)/review$', views.review, name = 'review'),
    re_path(r'^book/(?P<bid>[a-zA-Z0-9]+)/review/rate/(?P<rid>[0-9]+)$', views.rate_user_review, name = 'rate_user_review'),
    
    re_path(r'^book/(?P<bid>[a-zA-Z0-9]+)', views.book_details, name = 'book_details'),
    re_path(r'^search/$', views.search, name='search'),
    re_path(r'^search/filter-author$', views.search_filter_author, name='search_filter_author'),
    re_path(r'^search/filter-year$', views.search_filter_year, name='search_filter_year'),
    re_path(r'^search/filter-score$', views.search_filter_score, name='search_filter_score'),
    re_path(r'^keyword/(?P<key>[a-zA-Z0-9]+)/(?P<specified>.*)$', views.search_specific, name='search_specific'),
]

django-bookstore/db-project/db-project/urls.py
from django.urls import re_path, include
from django.contrib import admin

urlpatterns = [
    re_path(r'^polls/', include('polls.urls')),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^bookstore/', include('bookstore.urls')),
]

django-bookstore/db-project/polls/urls.py
from django.urls import re_path

from . import views

app_name = 'polls'
urlpatterns = [
    re_path(r'^$', views.index, name='index'),
]

django-bookstore/db-project/bookstore/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile, Book

class SearchForm(forms.Form):
    search_value = forms.CharField(label='Search', max_length=100)


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=True)

    class Meta:
        model = User
        fields = ['username', 'password', 'first_name', 'last_name']


class ProfileForm(forms.ModelForm):
    credit_card_number = forms.CharField(min_length=16, max_length=16, required=True)

    class Meta:
        model = Profile
        fields = ['credit_card_number', 'mailing_address', 'phone_number']


class LoginForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(widget=forms.PasswordInput)

class NewBookForm(forms.ModelForm):
    isbn13 = forms.CharField(label='ISBN13', min_length=13, max_length=13)
    isbn10 = forms.CharField(label='ISBN10', min_length=10, max_length=10)
    class Meta:
        model = Book
        fields = '__all__'

class AddCopiesForm(forms.Form):
    isbn13 = forms.CharField(label='ISBN13', min_length=13, max_length=13)
    num_copies = forms.IntegerField(label='Copies to add')

class StatisticsForm(forms.Form):
    month_choices = (
        ('1', 'Jan'),
        ('2', 'Feb'),
        ('3', 'Mar'),
        ('4', 'Apr'),
        ('5', 'May'),
        ('6', 'Jun'),
        ('7', 'Jul'),
        ('8', 'Aug'),
        ('9', 'Sep'),
        ('10', 'Oct'),
        ('11', 'Nov'),
        ('12', 'Dec')
    )

    month = forms.ChoiceField(choices=month_choices)
    view_top = forms.IntegerField(min_value=1)

django-bookstore/db-project/bookstore/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from .models import Book, Review, ShoppingCart, CustomerOrder, Rate
from django.db.models import Q, Sum, Count, Avg
import urllib
import xmltodict
import datetime
from operator import itemgetter

from django.views import generic
from django.views.generic import View
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.messages import get_messages

from django.urls import reverse
from django.http import HttpResponseRedirect

from django.db import IntegrityError

from .forms import SearchForm, UserRegistrationForm, ProfileForm, LoginForm, NewBookForm, AddCopiesForm, StatisticsForm

isbn_list_of_dicts = []

def home(request):
    #TODO: add functionality
    if request.user.is_authenticated:
        recommended = query(request.user.id, 'recommend')
        request.session['recommended'] = recommended
        request.session.modified = True

        # If there are no books bought yet or nothing to recommend
        if len(recommended) == 0:
            return render(request, 'bookstore/index.html', {'books': request.session['recommended'], 'flag': False})

        else:
            return render(request, 'bookstore/index.html', {'books': request.session['recommended'], 'flag': True})
    else:
        return render(request, 'bookstore/index.html', {'books': '', 'flag': False})


def search(request):
    """Book search based on authors, and/or publisher, and/or title, and/or subjec"""
    if request.method == 'GET':
        # create a form instance and populate it with data from the request:
        form = SearchForm(request.GET)
        # print (request.GET['search_value'])
        isbn_list_of_dicts = []

        # check whether it's valid:
        if form.is_valid():
            temp_dict = {}

            # Gets the search values, which is determined by what the user has typed into search bar
            search_values = form.cleaned_data['search_value'].split(" ")
            search_values = list(filter(None, search_values))

            #print ("Search form")
            #print (search_values)


            # calls the query function to get list of dictionaries of book data
            isbn_list_of_dicts = query(search_values, 'all')

    # No such results could be found
    if len(isbn_list_of_dicts) == 0:
        return render(request, 'bookstore/search_results.html', {'books': request.session['isbn_list_of_dicts'], 'status': 'No results could be found :('})

    request.session['isbn_list_of_dicts'] = isbn_list_of_dicts
    request.session.modified = True
    return render(request, 'bookstore/search_results.html', {'books': request.session['isbn_list_of_dicts'] , 'status': 'Search results for "%s"'%(' '.join(search_values))})

# Filters the search results by author
def search_filter_author(request):
    return render(request, 'bookstore/search_filter_author.html', {'books': request.session['isbn_list_of_dicts']})

# Filters the search results by year
def search_filter_year(request):
    return render(request, 'bookstore/search_filter_year.html', {'books': request.session['isbn_list_of_dicts']})

# Filters the search results by review_score
def search_filter_score(request):
    return render(request, 'bookstore/search_filter_score.html', {'books': request.session['isbn_list_of_dicts']})

# Returns a search result based on click event: Either by a certain publisher, author or category
def search_specific(request, key, specified):
    # Gets the search values, which is determined by the click event and returns a list of dictionaries
    search_values = [specified]
    isbn_list_of_dicts = query(search_values, key)
    request.session['isbn_list_of_dicts'] = isbn_list_of_dicts
    request.session.modified = True
    return render(request, 'bookstore/search_results.html', {'books': request.session['isbn_list_of_dicts'], 'status': 'Search results for "%s" under %s'%(' '.join(search_values), key)})

def query(search_values, query_type):
    # Get isbn hit count from book table
    isbn_list_of_dicts = []
    temp_dict = {}

    # Case when the recommender system is deployed
    if query_type == 'recommend':
        temp = []
        # get all orders of the current user
        search_user_books = CustomerOrder.objects.filter(login_name=search_values)
        # get all the isbn13 of these orders
        current_user_books = []
        current_user_books.extend(search_user_books.values_list('isbn13', flat=True))
        other_users = []

        # Gets the user id of the users who have ordered books that the user has ordered before
        for i in current_user_books:
            temp_users = CustomerOrder.objects.filter(isbn13=i)
            other_users.extend(temp_users.values_list('login_name', flat=True))

        # Removes the user's user id so that it will purely recommend new books
        other_users = list(set(other_users))
        if search_values in other_users:
            other_users.remove(search_values)

        # Gets the list of isbn13 that other users with similar taste have ordered
        temp_isbn13 = []
        for i in other_users:
            temp_other_user_books = CustomerOrder.objects.filter(login_name=i)
            temp_isbn13.extend(temp_other_user_books.values_list('isbn13', flat=True))

        # Gets the isbn10 of the books and removes the books that the user has ordered before
        for i in temp_isbn13:
            if i not in current_user_books:
                book = Book.objects.get(isbn13=i)
                temp.append(book.isbn10)

    else:
        for i in search_values:
            temp = []

            # Case when the user types into the search bar and searches
            if query_type == 'all':
                if ' '.join(search_values).count(';') != 3:
                    # Conjunctive search
                    # Gets the list of books' isbn10 that contain keywords from search bar
                    search_title = Book.objects.filter(title__icontains=i)
                    search_author = Book.objects.filter(author__icontains='')
                    search_publisher = Book.objects.filter(publisher__icontains=i)
                    search_subject = Book.objects.filter(book_subject__icontains=i)

                    temp.extend(search_title.values_list('isbn10', flat=True))
                    temp.extend(search_author.values_list('isbn10', flat=True))
                    temp.extend(search_publisher.values_list('isbn10', flat=True))
                    temp.extend(search_subject.values_list('isbn10', flat=True))

                    # Separated search
                    # Combines the list from the search back into the original sentence and split at commas instead
                    # index in final form refers to the following
                    # [title, author, publisher, category]
                else:
                    new_search_values = ' '.join(search_values).split(';')
                    search_dict = {'title':new_search_values[0],'author':new_search_values[1],'publisher':new_search_values[2],'subject':new_search_values[3]}
                    search_title = Q(title__icontains=new_search_values[0])
                    search_author = Q(author__icontains=new_search_values[1])
                    search_publisher = Q(publisher__icontains=new_search_values[2])
                    search_subject = Q(book_subject__icontains=new_search_values[3])

                    reference_list = {'title':search_title,'author':search_author,'publisher':search_publisher,'subject':search_subject}
                    queries = [search_title,search_author,search_publisher,search_subject]
                    # removes those fields with no user input
                    for i in search_dict:
                        if len(search_dict[i]) == 0:
                            queries.remove(reference_list[i])

                    print (queries)
                    if len(queries) == 0:
                        break

                    queries_and = ""

                    if len(queries) == 1:
                        queries_and = queries[0]
                        search_results = Book.objects.filter(queries_and)
                        temp.extend(search_results.values_list('isbn10', flat=True))

                    # if thhe queries len more than
                    elif len(queries) > 1:
                        queries_and = queries[0]
                    # AND the Q object with the ones remaining in the list
                        for item in queries[1:]:
                            queries_and &= item
                        search_results = Book.objects.filter(queries_and)
                        temp.extend(search_results.values_list('isbn10', flat=True))

                    print (queries_and)
                    break

            # Case when the user clicks an author
            elif query_type == 'author':
                # Gets the list of books' isbn10 written by a certain author
                search_author = Book.objects.filter(author__icontains=i)
                temp.extend(search_author.values_list('isbn10', flat=True))

            # Case when the user clicks a publisher
            elif query_type == 'publisher':
                # Gets the list of books' isbn10 published by a certain publisher
                search_publisher = Book.objects.filter(publisher__icontains=i)
                temp.extend(search_publisher.values_list('isbn10', flat=True))

            # Case when the user clicks a category
            elif query_type == 'category':
                # Gets the list of books' isbn10 from a certain category
                search_category_1 = Book.objects.filter(book_subject__icontains=i)

django-bookstore/db-project/bookstore/templates/bookstore/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Bookilicious | {% block title %}{% endblock %}</title>
    {% load static %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Sofia">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins">
    <link rel="stylesheet" type="text/css" href="{% static 'bookstore/css/bootstrap.min.css' %}" media="screen">
    <link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">
    <link rel="stylesheet" type="text/css" href="{% static 'bookstore/css/style.css' %}" media="screen"> {% block stylesheet %}{% endblock %}

</head>

<body>
    <nav id="nav" style="background-color: rgb(255, 255, 255);" class="navbar navbar-static-top justify-content-between">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
                <a class="navbar-brand" href="{% url 'bookstore:home' %}">Bookilicious</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <form class="navbar-form navbar-left" method="get" action="{% url 'bookstore:search' %}">
                    <div class="form-group">
                        <input type="text" class="form-control" name="search_value" maxlength="150" placeholder="Search: Title; Author; Publisher; Subject">
                    </div>
                    <button type="submit" class="btn btn-dark my-2 my-sm-0">Search</button>
                </form>
                <ul class="nav navbar-nav navbar-right">
                    {% if not user.is_anonymous %} {% if user.is_staff %}
                    <li><a href="{% url 'bookstore:stats' %}">Stats</a></li>
                    <li><a href="{% url 'bookstore:admin' %}">Admin</a></li>
                    {% endif %}
                    <li><a href="{% url 'bookstore:cart' %}">Cart</a></li>
                    <li><a href="{% url 'bookstore:account' %}">Account</a></li>
                    <li><a href="{% url 'bookstore:logout' %}">Logout</a></li>
                    {% else %}
                    <li><a href="{% url 'bookstore:login' %}?next={% firstof request.path '/' %}">Login</a></li>
                    <li><a href="{% url 'bookstore:register' %}">Register</a></li>
                    {% endif %}
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

    {% block body %} {% endblock %}

    <script type='text/javascript' src="{% static 'bookstore/js/jquery-3.1.1.min.js' %}"></script>
    <script type='text/javascript' src="{% static 'bookstore/js/bootstrap.min.js' %}"></script>

</body>

</html>

django-bookstore/db-project/bookstore/templates/bookstore/form-template.html
{% for field in form %}
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <span class="text-danger small">{{ field.errors }}</span>
    </div>
    <label class="control-label col-sm-3" style="text-align: left;">{{ field.label_tag }}</label>
    <div id="form-parent" class="col-sm-8 col-md-8">{{ field }}</div>
</div>
{% endfor %}

django-bookstore/db-project/bookstore/templates/bookstore/index.html
{% extends 'bookstore/base.html' %} {% block title %}Home{% endblock %} {% load static %} {% block stylesheet %}
<link rel="stylesheet" type="text/css" href="{% static 'bookstore/css/index.css'  %}">
<link rel="stylesheet" type="text/css" href="{% static 'bookstore/css/search-results.css'  %}"> {% endblock %} {% block body %}

<div class="home__header container">
    <div class="row">
        <div class="col-sm-12" style="background:rgb(255, 255, 255); border-radius:15px; padding: 15px 0px 15px 0px">
            {% if book_in_cart %}
            <h4 class="success-message">You have successfully added {{book_in_cart}} into Cart</h4>
            {% endif %}
            <h1>Bookilicious</h1>
            <h5>A world of unique portable magic</h5>
            {% if not user.is_anonymous %}
            <h3 style="clear:left">Hello {{ user.first_name }}</h3>
            {% endif %}
        </div>
    </div>
</div>

<div class="rig">
    <ul id="rig">
        <li>
            <a class="rig-cell" href="{% url 'bookstore:search_specific' 'category' 'arts' %}">
                <img class="rig-img" src="{% static  'img/img-arts.jpg'   %}">
                <span class="rig-overlay"></span>
                <span class="rig-text">Arts</span>
            </a>
        </li>
        <li>
            <a class="rig-cell" href="{% url 'bookstore:search_specific' 'category' 'accounting' %}">
                <img class="rig-img" src="{% static 'img/img-accounting.jpg'  %}">
                <span class="rig-overlay"></span>
                <span class="rig-text">Accounting</span>
            </a>
        </li>
        <li>
            <a class="rig-cell" href="{% url 'bookstore:search_specific' 'category' 'business' %}">
                <img class="rig-img" src="{% static  'img/img-business.jpg'   %}">
                <span class="rig-overlay"></span>
                <span class="rig-text">Business</span>
            </a>
        </li>
        <li>
            <a class="rig-cell" href="{% url 'bookstore:search_specific' 'category' 'essay' %}">
                <img class="rig-img" src="{% static  'img/img-essay.jpg'   %}">
                <span class="rig-overlay"></span>
                <span class="rig-text">Essay</span>
            </a>
        </li>
        <li>
            <a class="rig-cell" href="{% url 'bookstore:search_specific' 'category' 'general' %}">
                <img class="rig-img" src="{% static  'img/img-help.jpg'   %}">
                <span class="rig-overlay"></span>
                <span class="rig-text">General</span>
            </a>
        </li>
        <li>
            <a class="rig-cell" href="{% url 'bookstore:search_specific' 'category' 'journal' %}">
                <img class="rig-img" src="{% static  'img/img-journal.jpg'   %}">
                <span class="rig-overlay"></span>
                <span class="rig-text">Journalism</span>
            </a>
        </li>
        <li>
            <a class="rig-cell" href="{% url 'bookstore:search_specific' 'category' 'memoir' %}">
                <img class="rig-img" src="{% static  'img/img-memoir.jpg'   %}">
                <span class="rig-overlay"></span>
                <span class="rig-text">Memoir</span>
            </a>
        </li>
        <li>
            <a class="rig-cell" href="{% url 'bookstore:search_specific' 'category' 'nonfiction' %}">
                <img class="rig-img" src="{% static  'img/img-nonfiction.jpg'   %}">
                <span class="rig-overlay"></span>
                <span class="rig-text">Nonfiction</span>
            </a>
        </li>
        <li>
            <a class="rig-cell" href="{% url 'bookstore:search_specific' 'category' 'reference' %}">
                <img class="rig-img" src="{% static  'img/img-reference.jpg'   %}">
                <span class="rig-overlay"></span>
                <span class="rig-text">Reference Books</span>
            </a>
        </li>
        <li>
            <a class="rig-cell" href="{% url 'bookstore:search_specific' 'category' 'science' %}">
                <img class="rig-img" src="{% static  'img/img-science.jpg'   %}">
                <span class="rig-overlay"></span>
                <span class="rig-text">Science</span>
            </a>
        </li>
        <li>
            <a class="rig-cell" href="{% url 'bookstore:search_specific' 'category' 'society' %}">
                <img class="rig-img" src="{% static  'img/img-society.jpg'   %}">
                <span class="rig-overlay"></span>
                <span class="rig-text">Society</span>
            </a>
        </li>
        <li>
            <a class="rig-cell" href="{% url 'bookstore:search_specific' 'category' 'textbook' %}">
                <img class="rig-img" src="{% static  'img/img-textbook.jpg'   %}">
                <span class="rig-overlay"></span>
                <span class="rig-text">Textbook</span>
            </a>
        </li>
    </ul>
</div>

{% if not user.is_anonymous and flag == True%}
<div class="container">
    <div class="row">
        <h1>Recommendations</h1>
        <h5>Other readers who bought the same books as you, also bought:</h5>
    </div>
    <div class="row">
        <div class="col-sm-12">
            {% for book in books|dictsortreversed:"data.hits"%}
            <div class="perrow">
                <div id="column1">
                    <img src={{book.data.url}} class="recommend-img">
                    <!-- dict sort django -->
                </div>
                <div id="column2">
                    Title: <a href="{% url 'bookstore:book_details' book.isbn10 %}">{{ book.data.title }}</a><br> Author: <a href="{% url 'bookstore:search_specific' 'author' book.data.author %}">{{ book.data.author }}</a><br> Publisher: <a href="{% url 'bookstore:search_specific' 'publisher' book.data.publisher %}">{{ book.data.publisher }}</a><br>                    Year: {{ book.data.year }}
                </div>
                <div class="clear"></div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endif %} {% endblock %}

django-bookstore/db-project/bookstore/templates/bookstore/search_filter_author.html
{% extends 'bookstore/base.html' %}
{% block title %}Search Results{% endblock %}
{% load static %}
{% block stylesheet %}
<link rel="stylesheet" type="text/css" href="{% static 'bookstore/css/search-results.css'  %}">
{% endblock %}
{% block body %}

<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h1>Search Results</h1>
    </div>
  </div>
  <div class="sort-by">
    <p>Sort by:</p>
    <a>Author | </a>
    <a href="{% url 'bookstore:search_filter_score' %}">User Rating | </a>
    <a href="{% url 'bookstore:search_filter_year' %}">Year | </a>
  </div>
  <div class="row">
    <div class="col-sm-12">
      {% for book in books|dictsort:"data.author"%}
            <div id="column1">
                <img src={{book.data.url}}>
            <!-- dict sort django -->
            </div>
          <div id="column2">
            Title: <a href="{% url 'bookstore:book_details' book.isbn10 %}">{{ book.data.title }}</a><br>
            Author: <a href="{% url 'bookstore:search_specific' 'author' book.data.author %}">{{ book.data.author }}</a><br>
            Publisher: <a href="{% url 'bookstore:search_specific' 'publisher' book.data.publisher %}">{{ book.data.publisher }}</a><br>
            Year: {{ book.data.year }}
        </div>
        <div class="clear"></div>
      {% endfor %}
    </div>
  </div>
</div>

{% endblock %}

django-bookstore/db-project/bookstore/templates/bookstore/search_filter_score.html
{% extends 'bookstore/base.html' %}
{% block title %}Search Results{% endblock %}
{% load static %}
{% block stylesheet %}
<link rel="stylesheet" type="text/css" href="{% static 'bookstore/css/search-results.css'  %}">
{% endblock %}
{% block body %}

<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h1>Search Results</h1>
    </div>
  </div>
  <div class="sort-by">
    <p>Sort by:</p>
    <a href="{% url 'bookstore:search_filter_author' %}">Author | </a>
    <a>User Rating | </a>
    <a href="{% url 'bookstore:search_filter_year' %}">Year | </a>
  </div>
  <div class="row">
    <div class="col-sm-12">
      {% for book in books|dictsortreversed:"data.average_score"%}
            <div id="column1">
                <img src={{book.data.url}}>
            <!-- dict sort django -->
            </div>
          <div id="column2">
            Title: <a href="{% url 'bookstore:book_details' book.isbn10 %}">{{ book.data.title }}</a><br>
            Author: <a href="{% url 'bookstore:search_specific' 'author' book.data.author %}">{{ book.data.author }}</a><br>
            Publisher: <a href="{% url 'bookstore:search_specific' 'publisher' book.data.publisher %}">{{ book.data.publisher }}</a><br>
            Year: {{ book.data.year }}
        </div>
        <div class="clear"></div>
      {% endfor %}
    </div>
  </div>
</div>

{% endblock %}

django-bookstore/db-project/bookstore/templates/bookstore/search_filter_year.html
{% extends 'bookstore/base.html' %}
{% block title %}Search Results{% endblock %}
{% load static %}
{% block stylesheet %}
<link rel="stylesheet" type="text/css" href="{% static 'bookstore/css/search-results.css'  %}">
{% endblock %}
{% block body %}

<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h1>Search Results</h1>
    </div>
  </div>
  <div class="sort-by">
    <p>Sort by:</p>
    <a href="{% url 'bookstore:search_filter_author' %}">Author | </a>
    <a href="{% url 'bookstore:search_filter_score' %}">User Rating | </a>
    <a>Year | </a>
  </div>
  <div class="row">
    <div class="col-sm-12">
      {% for book in books|dictsortreversed:"data.year"%}
            <div id="column1">
                <img src={{book.data.url}}>
            <!-- dict sort django -->
            </div>
          <div id="column2">
            Title: <a href="{% url 'bookstore:book_details' book.isbn10 %}">{{ book.data.title }}</a><br>
            Author: <a href="{% url 'bookstore:search_specific' 'author' book.data.author %}">{{ book.data.author }}</a><br>
            Publisher: <a href="{% url 'bookstore:search_specific' 'publisher' book.data.publisher %}">{{ book.data.publisher }}</a><br>
            Year: {{ book.data.year }}
        </div>
        <div class="clear"></div>
      {% endfor %}
    </div>
  </div>
</div>

{% endblock %}

django-bookstore/db-project/bookstore/templates/bookstore/search_results.html
{% extends 'bookstore/base.html' %} {% block title %}Search Results{% endblock %} {% load static %} {% block stylesheet %}
<link rel="stylesheet" type="text/css" href="{% static 'bookstore/css/search-results.css'  %}"> {% endblock %} {% block body %}

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h1>Search Results</h1>
            <p>{{status}}</p>
        </div>
    </div>
    <div class="sort-by">
        <p>Sort by:</p>
        <a href="{% url 'bookstore:search_filter_author' %}">Author | </a>
        <a href="{% url 'bookstore:search_filter_score' %}">User Rating | </a>
        <a href="{% url 'bookstore:search_filter_year' %}">Year | </a>
    </div>
    <div class="row">
        <div class="col-sm-12">
            {% for book in books|dictsortreversed:"data.hits"%}
            <div class="perrow">
                <div id="column1">
                    <img src={{book.data.url}}>
                    <!-- dict sort django -->
                </div>
                <div id="column2">
                    <div>Title:</div> <a href="{% url 'bookstore:book_details' book.isbn10 %}">{{ book.data.title }}</a><br>
                    <div>Author:</div> <a href="{% url 'bookstore:search_specific' 'author' book.data.author %}">{{ book.data.author }}</a><br>
                    <div>Publisher:</div> <a href="{% url 'bookstore:search_specific' 'publisher' book.data.publisher %}">{{ book.data.publisher }}</a><br>
                    <div>Year: {{ book.data.year }}
                    </div>
                </div>
                <div class="clear"></div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}